### ISSUE TITLE
Typo on documentation

### ISSUE THREAD

**Issue by cwang22** [SocialiteProviders/PayPal-Sandbox#1]
in the [documentation](http://socialiteproviders.github.io/providers/paypal-sandbox/)

**installation**

`composer require socialiteproviders/paypal_sandbox`

should be

`composer require socialiteproviders/paypal-sandbox`

**usage**

`return Socialite::with('paypal sandbox')->redirect();`

should be

`return Socialite::with('paypal_sandbox')->redirect();`

**Comment by AndyWendt** [comment]
@cwang22 Thank you for this!

**Comment by AndyWendt** [comment]
fixed
